spring:
  datasource:
    url: jdbc:postgresql://localhost/dbCert
    username: postgres
    password: 1234
  jpa:
    generate-ddl: true

role:
  values: CVCA, DV

type:
  values: IS

signatureAlgorithm:
  values: ECDSA_SHA_256

connectConfigs:
  PORT: 8081
  IP: "localhost"


