spring:
  datasource:
    url: jdbc:postgresql://localhost/dbCert
    username: postgres
    password: 1234
  jpa:
    generate-ddl: true

role:
  values: CVCA, DV

type:
  values: IS

signatureAlgorithm:
  values: SHA

connectConfigs:
  PORT: 8080
  IP: localhost


